name: Run Typst Script and Release PDFs

on:
  push:
    branches:
      - main  # 监听 main 分支的 push 事件
  workflow_dispatch:  # 允许手动触发


jobs:
  build-and-release:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 拉取仓库代码

      - name: Set up Typst
        run: |
          # 安装 typst 编译器
          sudo apt update
          sudo apt install -y curl unzip
          curl -L https://github.com/typst/typst/releases/latest/download/typst-linux.zip -o typst.zip
          unzip typst.zip -d /usr/local/bin
          rm typst.zip
          typst --version  # 检查安装是否成功

      - name: Run Typst Script
        run: |
          # 赋予脚本执行权限并运行
          chmod +x run_typst.sh
          ./run_typst.sh

      - name: Upload ZIP file to GitHub release
        uses: actions/upload-artifact@v3
        with:
          name: compiled_pdfs
          path: compiled_pdfs.zip  # 上传生成的 zip 文件